if !exists('g:vimrc_initialized')
  let g:is_windows = has('win32') || has('win64')
  if empty($MYVIMRC)
    let $MYVIMRC = substitute($VIMINIT, "^source ", "", "g")
  endif
  let g:rc_dir = strpart($MYVIMRC, 0, strridx($MYVIMRC, (g:is_windows ? '\' : '/'))).'/.vim'
  let $RCDIR = g:rc_dir
  let g:plugins_dir = g:rc_dir.'/plugged'
  let g:autoload_dir = g:rc_dir.'/autoload'
"  let g:vim_plug_dir = g:plugins_dir.'/vim-plug'
"  let &runtimepath = g:rc_dir.','.g:vim_plug_dir.','.$VIMRUNTIME
  let &runtimepath = g:rc_dir.','.$VIMRUNTIME.',/usr/share/vim/vimfiles'
  let g:vimrc_initialized = 1
endif

" Plugins " {{{

" Install vim-plug if not available {{{
if !isdirectory(g:autoload_dir)
  call mkdir(g:autoload_dir, 'p')
endif

" OLD -> was not identified as a plugin (because of extra autoload dir)
" would be nice if I found a workaround to update vim-plug using itself
"if !isdirectory(g:vim_plug_dir.'/autoload')
"  execute '!git clone git://github.com/junegunn/vim-plug '
"        \ shellescape(g:vim_plug_dir.'/autoload', 1)

if empty(glob(g:autoload_dir."/plug.vim"))
  execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.github.com/junegunn/vim-plug/master/plug.vim'
  " TODO: automatically call PlugInstall (how?)
endif


call plug#begin(g:plugins_dir)



" TO TEST:
" Plug 'Shougo/denite.nvim'

" TEST AGAIN: 
"Plug 'Shougo/vinarise'
"Plug 'mbbill/undotree', { 'on': 'UndotreeToggle' }

"Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"Plug 'OmniSharp/omnisharp-vim'
"Plug 'cyansprite/omnisharp.nvim', { 'do': './install.sh' }
"Plug 'dimixar/deoplete-omnisharp'



"Plug 'junegunn/vim-plug'

" Colorscheme
Plug 'naumazeredo/vim-kogy-colorscheme'

" General
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'Yggdroot/indentLine' ", {'on': 'IndentLinesEnable'}
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

"Plug 'luochen1990/rainbow'
Plug 'terryma/vim-multiple-cursors'

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'naumazeredo/vim-unity3d-snippets'
Plug 'naumazeredo/vim-testlib-snippets'

Plug 'Valloric/YouCompleteMe', { 'do': './install.py --clang-completer --cs-completer' }

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

Plug 'benekastah/neomake'

" Motion
Plug 'vim-scripts/lastpos.vim'
Plug 'junegunn/vim-easy-align', { 'on': ['<Plug>(EasyAlign)', 'EasyAlign'] }
Plug 'Lokaltog/vim-easymotion'

" Language specific

Plug 'sheerun/vim-polyglot'

Plug 'derekwyatt/vim-fswitch', { 'for': ['c', 'cpp'] }

Plug 'plasticboy/vim-markdown', { 'for': ['markdown'] }
"Plug 'mattn/emmet-vim' ", { 'on': 'html' }
"Plug 'gregsexton/MatchTag', { 'on': 'html' }

Plug 'Glench/Vim-Jinja2-Syntax', { 'for': ['html'] }

Plug 'tikhomirov/vim-glsl'
Plug 'beyondmarc/hlsl.vim'
Plug 'vim-scripts/cg.vim'
Plug 'vim-scripts/ShaderHighLight'

call plug#end()

" " }}}

" General "{{{

set encoding=utf-8

syntax on

set history=500                " Number of things to remember in history.
set timeoutlen=200
"set timeoutlen=3000
set ttimeoutlen=10
set clipboard+=unnamedplus     " Yanks go on clipboard instead.

set autoread

set nobackup
set nowritebackup
set noswapfile

set ignorecase                 " be case insensitive when searching
set smartcase                  " be case sensitive when input has a capital
                               " letter

let mapleader = ','
let maplocalleader = '	'      " Tab as a local leader

set lazyredraw
set scrolloff=10

"set mouse=a
set mouse=

set modeline

set shortmess+=c

" " }}}

" Formating "{{{

"set textwidth=80
set textwidth=0

"set wrap
set nowrap
set whichwrap+=<,>,h,l

set tabstop=2                  " tab size eql 2 spaces
set softtabstop=2
set shiftwidth=2                  " tab size eql 2 spaces
set expandtab                  " replace tabs with ${tabstop} spaces

set noshowmode                 " Don't show mode on bottom

set foldmethod=indent
set nofoldenable

"set cindent
set indentkeys-=0#            " do not break indent on #
set cinkeys-=0#
set cinkeys+=0=break
set cinoptions=:s,cs
set cinoptions+=b1,g0,N-s,t0,(0,Ws
set cinoptions+=i2s,m1
set cinwords=if,else,while,do
set cinwords+=for,switch,case

" " }}}

" Visual "{{{

set t_Co=256

colorscheme kogyblack
set background=dark

set number

set cursorline                " Current line adornment

set showcmd                   " display an incomplete command in statusline

set showmatch                 " Show matching brackets.
set matchtime=2

set splitbelow
set splitright

set list listchars=tab:»\ ,trail:·,precedes:<,extends:>
set showbreak=↪
"set breakindent breakindentopt=sbr

set conceallevel=0

" " }}}

" Key mappings " {{{

nnoremap ; :
vnoremap ; :

nnoremap <silent> ,. :noh<cr>
vnoremap ,. <esc>
inoremap ,. <esc>

" split line (opposite to <s-j> joining line)
nnoremap <s-k> i<CR><ESC>

" fast scrolling
noremap <silent> <c-j> 15gj
noremap <silent> <c-k> 15gk

" switch between windows (like <c-w> h, etc)
nnoremap <leader>h <c-w>h
nnoremap <leader>j <c-w>j
nnoremap <leader>k <c-w>k
nnoremap <leader>l <c-w>l

nnoremap H g^
nnoremap L g$

" execute current line or selection
nnoremap <silent> <leader>t "ryy:@r<cr>
vnoremap <silent> <leader>t "rygy:@r<cr>

" toggle spell on/off
"nnoremap <silent> <leader>s :set spell!<cr>

" edit vimrc
"nnoremap <leader>e :e $MYVIMRC<cr>
"nnoremap <leader>r :source $MYVIMRC<cr>

" search/replace the word under the cursor
nnoremap <leader>z :let @z = expand("<cword>")<cr>q:i%s/\C\v<<esc>"zpa>//g<esc>hi

" move text up/down
"nnoremap <silent> <m-j> :m .+1<cr>==
"nnoremap <silent> <m-k> :m .-2<cr>==
"vnoremap <silent> <m-j> :m '>+1<cr>gv=gv
"vnoremap <silent> <m-k> :m '<-2<cr>gv=gv

" " }}}

" AutoCommands " {{{
augroup vimrc_autocmds
  au Filetype markdown setl tw=80 wrap
  au FileType python setl tabstop=4 softtabstop=4 shiftwidth=4 "expandtab
  au FileType csharp setl tabstop=2 softtabstop=2 shiftwidth=2 cinoptions+=N0
  au FileType c,cpp setl cindent
  au FileType javascript setl tabstop=2 softtabstop=2 shiftwidth=2
  au FileType html setl tabstop=2 softtabstop=2 shiftwidth=2 nowrap tw=0

  " PICO-8
  au BufRead {*.p8} setl ft=lua tabstop=1 softtabstop=1 shiftwidth=1 expandtab

  " open help in vertical split
  au BufWinEnter *.txt if &ft == 'help' | wincmd H | nmap q :q<CR> | endif

  " Some formats doesn't set fo properly, so we need this autocmd
  autocmd FileType * setlocal formatoptions-=cro
augroup END

" " }}}

" Scripts and Plugins Mappings " {{{

" Reloads file if changed outside (since autoread doesn't work)
autocmd FocusGained * silent! checktime

" Remove trailing mantaining cursor position
fun! StripTrailingWhitespaces()
  if !&binary && &filetype != 'diff'
    normal mz
    "normal Hmz
    %s/\s\+$//e
    "normal 'yz<CR>
    normal `z
  endif
endfunction

nnoremap <silent> <leader>ws :call StripTrailingWhitespaces()<cr>


" Fugitive {{{
nnoremap <leader>gs :Gstatus<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gb :Gblame<cr>
nnoremap <leader>gw :Gwrite
nnoremap <leader>gr :Gread
nnoremap <leader>dp :diffput<cr>:diffupdate<cr>
vnoremap <leader>dp :diffput<cr>:diffupdate<cr>
nnoremap <leader>dg :diffget<cr>:diffupdate<cr>
vnoremap <leader>dg :diffget<cr>:diffupdate<cr>
" }}}

" YouCompleteMe {{{
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
"let g:ycm_global_ycm_extra_conf = '/usr/share/vim/vimfiles/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'

"au FileType cpp let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_cpp_extra_conf.py'
"au FileType c let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_c_extra_conf.py'
" }}}


" NeoMake {{{
"let g:neomake_verbose = 0
"au! BufWritePost * Neomake
call neomake#configure#automake('rw')
let g:neomake_python_pylint_args = neomake#makers#ft#python#pylint()['args'] + ["-d", "missing-docstring,invalid-name", "--ignored-modules", "flask_sqlalchemy", "--ignored-classes", "scoped_session"]
" }}}

" Indent line {{{
let g:indentLine_enabled = 1
"let g:indentLine_color_term = 235
let g:indentLine_char = '│'
let g:indentLine_setConceal = 0
" }}}

" Easy Align {{{
vmap <Enter>          <Plug>(EasyAlign)
vmap <Leader><Enter>  <Plug>(LiveEasyAlign)
" }}}

" Easy Motion {{{
let g:EasyMotion_leader_key='<localleader>'
nmap <LocalLeader>h <Plug>(easymotion-linebackward)
nmap <LocalLeader>j <Plug>(easymotion-j)
nmap <LocalLeader>k <Plug>(easymotion-k)
nmap <LocalLeader>l <Plug>(easymotion-lineforward)
" }}}

" Airline {{{
let g:airline_powerline_fonts = 1
let g:airline_theme='badcat'
"let g:airline_left_sep = ''
"let g:airline_right_sep = ''
" }}}

" Fugitive {{{
set diffopt+=vertical
" }}}

" FSwitch {{{
" nnoremap <leader>s  :FSHere<CR>
nnoremap <leader>sj :FSHere<CR>
nnoremap <leader>sl :FSSplitRight<CR>
nnoremap <leader>sh :FSSplitLeft<CR>
" }}}

" NERDTree {{{
map <localleader>n :NERDTreeToggle<cr><c-w>=
let NERDTreeIgnore = ['\.meta$']
" }}}

" Snippets {{{
let g:UltiSnipsEditSplit = 'normal'
let g:UltiSnipsSnippetsDir = '~/.vim/UltiSnips'
"let g:UltiSnipsSnippetsDir = g:rc_dir . '/UltiSnips'
"let g:UltiSnipsExpandTrigger = "<c-s>"
let g:UltiSnipsExpandTrigger = "<leader>s"
let g:UltiSnipsJumpForwardTrigger = "<leader>n"
" }}}

" FZF {{{
if has('nvim')
  let $FZF_DEFAULT_OPTS .= ' --inline-info'
endif

nnoremap <silent> <leader><leader> :Files<cr>
nnoremap <silent> <leader>b :Buffers<cr>
" }}}

" Markdown {{{
let g:vim_markdown_conceal = 0
" }}}

" JSON {{{
let g:vim_json_syntax_conceal = 0
" }}}


" Deoplete {{{
"let g:deoplete#enable_at_startup = 1
"
"inoremap <silent><expr> <TAB>
"    \ pumvisible() ? "\<C-n>" :
"    \ <SID>check_back_space() ? "\<TAB>" :
"    \ deoplete#mappings#manual_complete()
"function! s:check_back_space() abort "{{{
"    let col = col('.') - 1
"    return !col || getline('.')[col - 1]  =~ '\s'
"endfunction "}}}
" }}}

" Emmet {{{
"let g:user_emmet_leader_key='<c-f>'
" }}}

" Rainbow {{{
"let g:rainbow_active = 1
" }}}

" Omnisharp {{{
"let g:deoplete_omnisharp_exe_path = '/opt/omnisharp-roslyn/OmniSharp.exe'
" }}}

" UndoTree {{{
"nnoremap <leader>u :UndotreeToggle<cr>
" }}}


" " }}}
